/**
 * Shared user pool for all k6 scenarios.
 * Loads from k6/data/users.json (generated by seed-load-test.ts).
 * Each entry: { userId, sessionToken, promptId?, groupChatId? }
 */
import { SharedArray } from 'k6/data';

export const users = new SharedArray('load-test-users', function () {
  // open() path is relative to THIS file (k6/lib/)
  return JSON.parse(open('../data/users.json'));
});

/** Pick the user for the current VU (round-robin). */
export function pickUser() {
  return users[(__VU - 1) % users.length];
}

/** Return headers with the user's session cookie + JSON content type. */
export function authHeaders(user) {
  return {
    'Content-Type': 'application/json',
    'Cookie': `better-auth.session_token=${user.sessionToken}`,
  };
}
